<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
	<ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
	<AssemblyTitle></AssemblyTitle>
	<ApplicationIcon>icone.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="icone.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERSistemas.Application\ERSistemas.Application.csproj" />
    <ProjectReference Include="..\ERSistemas.Infrastructure\ERSistemas.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>