<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERSistemas.Application\ERSistemas.Application.csproj" />
    <ProjectReference Include="..\ERSistemas.Domain\ERSistemas.Domain.csproj" />
  </ItemGroup>
</Project>
